language: ruby
sudo: false
rvm:
  - 2.3.1
before_install:

script:
  - bundle exec rspec spec
before_script:
  - cp config/database_example.yml config/database.yml
  - cp config/secrets.example.yml config/secrets.yml
  - psql -c 'create database buzz_test' -U postgres
  - psql -c 'create role root superuser createdb createrole inherit login replication' -U postgres
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
cache:
  bundler: true
  directories:

addons:
  postgresql: "9.4"
services:
  - postgresql
notifications:
  hipchat:
    on_success: change
    on_failure: change
    notify: true
    rooms:
      secure: JyXM6Tb27tNx38Pd4BH7ClCRuAYrajmYBWAbFDGRDWSSvpFJyouPIrs90fEgQd3FVnr7QV1Y1qdJsInPAK7NokACXOjk7sEb7ibXyZzy+q4rsGffVK6lL+5eYBEw2JL1ZZwa5O3l5TkDDnyexou3GVbhTAbRS84JmlmunbbZhVs=
