version: 0.2

phases:
  pre_build:
    commands:
      - echo Build started...
  build:
    commands:
      - echo Building...
      - bundle install --deployment
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
