---
- name: Deploy Buzz infrastructure build using Cloudformation
  hosts:
# LibND - Virginia
    - buzz-prep-service-libnd
    - buzz-prod-service-libnd
#Testlibnd - Oregon
#    - buzz-prep-oregon
#    - buzz-prod-oregon
  connection: local
  gather_facts: false
  become: false
  vars:
    template: cloudformation/service.yml
    template_parameters:
      AppEnvPath: '{{ AppEnvPath }}'
      ContainerCpu: '{{ ContainerCPU }}'
      ContainerMemory: '{{ ContainerMemory }}'
      DesiredCount: '{{ DesiredCount }}'
      ImageUrl: '{{ ImageURL }}'
      InfrastructureStackName: '{{ tagService }}-app-infrastructure'
      NetworkStackName: '{{ NetworkStackName }}'
      Path: '{{ lb_path }}'
      Priority: '{{ lb_route_priority }}'
    stack_tags:
      Name: '{{ tagName }}-{{ tagEnvironment }}'
      Owner: '{{ tagOwner }}'
      Contact: '{{ tagContact }}'
      Description: '{{ tagDescription }}'
      Service: '{{ tagService }}'
      FQDN: '{{ host }}'
      TemplateSource: 'https://github.com:{{ repository }}/deploy/files/{{ template }}'
      ProjectName: '{{ tagName }}'
      TemplateVersion: 'Some_version_determined_later'
  tasks:
    - name: Launch application infrastructure Cloud Formation
      cloudformation:
        state: present
        template: '{{ template }}'
        stack_name: '{{ tagService }}-service-{{ tagEnvironment }}'
        template_parameters: '{{ template_parameters }}'
        tags: '{{ stack_tags }}'
