---
- name: Deploy Buzz pipeline build using CloudFormation
  hosts:
    - buzz-prep-oregon
  connection: local
  gather_facts: false
  become: false
  vars_files:
    - ./vars/oauth.yml
  vars:
    template: files/service-pipeline.yml
    template_parameters:
      Approvers: '{{ Approvers }}'
      CDBranchName: '{{ CDBranchName }}'
      ContactTag: '{{ tagContact }}'
      InfrastructureStackName: '{{ tagService }}-app-infrastructure'
      NameTag: '{{ tagName }}-servicepipeline-{{ tagEnvironment }}'
      OAuth: '{{ OAuth_token }}'
      OwnerTag: '{{ tagOwner }}'
      ProdServiceStackName: '{{ tagService }}-service-prod'
      TestServiceStackName: '{{ tagService }}-service-prep'
      TestUrlPath: '{{ TestUrlPath }}'
    stack_tags:
      Name: '{{ tagName }}'
      Owner: '{{ tagOwner }}'
      Contact: '{{ tagContact }}'
      Description: '{{ tagDescription }}'
      Service: '{{ tagService }}'
      FQDN: '{{ host }}'
  tasks:
    - name: Launch application infrastructure Cloud Formation
      cloudformation:
        state: present
        template: '{{ template }}'
        stack_name: '{{ tagService }}-service-pipeline'
        template_parameters: '{{ template_parameters }}'
        tags: '{{ stack_tags }}'
      register: aws_cf_stack
