---
# Tag variables - used for all CloudFormations
tagName: testlibnd-buzz
tagContact: lib-esu-group@nd.edu
tagDescription: 'Buzz application pipeline'
tagEnvironment: prod
tagOwner: hanstra
tagService: "buzz"
# Pipeline variables
Approvers: jgondron@nd.edu
CDBranchName: th_dockerize
TestUrlPath: /all/stacks/buzz-service-prep/url
PrepEnvPath: all/buzz/prep
ProdEnvPath: all/buzz/prod
# Network variables
vpc_id: vpc-07ee54d622c5c8d47
RDSSecurityGroup: sg-0e1859505f96c6548
private_subnet1: subnet-0c9bf404af7084f0a
private_subnet2: subnet-0296ce94fcb425673
public_subnet1: subnet-0cc5aae8fd96cbb8b
public_subnet2: subnet-0134c4c2fbf3a608a
...
