# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby $ {{ matrix.ruby-version }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:9.4.26
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        
    
    strategy:
      matrix:
        ruby-version: [2.3, 2.4, 2.5, 2.6, 2.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby-version }}
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Pre-Build Commands
      run: |
        cp config/database_example.yml config/database.yml
        cp config/secrets.example.yml config/secrets.yml
        host postgres
    - name: Install Bundler
      run: gem install bundler:1.17.3
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake
